conda-forge/evalml-core-feedstock

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, README.md, build-locally.py, recipe/meta.yaml
Add woodwork dependency
Checklist
=> Add woodwork dependency.

.ci_support/linux_64_.yaml, README.md, recipe/meta.yaml
=> Update URLs, bump build number

.ci_support/linux_64_.yaml, recipe/meta.yaml
=> Setting woodwork==0.0.7

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
Checklist
Updates plotly version to 4.14.1 to support kaleido 0.1.0
=> Update plotly kaleido

.ci_support/linux_64_.yaml, recipe/meta.yaml
=> Cap sklearn at < 0.24.0

recipe/meta.yaml
=> Cap python graphviz < 0.16 and pandas < 1.2.0

recipe/meta.yaml
=> Add Parthiv Naresh to list of maintainers

recipe/meta.yaml
=> Add angela97lin as maintainer

recipe/meta.yaml
=> Updating release 0.17.0

recipe/meta.yaml
=> update version and add bchen1116 to maintainers

.scripts/build_steps.sh, .scripts/logging_utils.sh, .scripts/run_docker_build.sh, README.md, recipe/meta.yaml
=> 0.23.0 h23f007

recipe/meta.yaml
Related issue [here](https://github.com/alteryx/evalml/issues/2208)
Checklist
=> Networkx dependency

recipe/meta.yaml
=> Fix duplicates

recipe/meta.yaml
Reverting the feedstock to its original state before the date feature PR
Checklist
=> revert to original

recipe/meta.yaml
=> Pin XGBoost version

recipe/meta.yaml
Upgraded the woodwork version to 0.3.1.
=> Upgraded the woodwork version.

recipe/meta.yaml
=> Ignore parallel tests instead of nonexistent dask tests

.github/check_versions.py, .github/workflows/check_versions.yml, recipe/meta.yaml
=> Add CI to check versions match latest_release_changes

recipe/meta.yaml
=> 0.41.0 update

recipe/meta.yaml
=> Upgrade EvalML 0.45.0

.github/CODEOWNERS, recipe/meta.yaml
Wishing @angela97lin the best!
Checklist
=> Update code owners / maintainers

.github/CODEOWNERS, README.md, recipe/meta.yaml
=> Add fjlanasa as maintainer

recipe/meta.yaml
=> move vowpalwabbit from evalml-core to evalml

.github/CODEOWNERS, README.md, recipe/meta.yaml
=> Add to list of contributors
